version: '3.8'

services:
  # DỊCH VỤ 1: HADOOP (NAMENODE)
  hadoop:
    build:
      context: .
      dockerfile: docker/hadoop/Dockerfile
    hostname: namenode
    volumes:
      - hadoop_data:/usr/local/hadoop/data
    networks:
      - hadoop_network
    ports:
      - "9870:9870"
      - "50070:50070" 
    command: bash /opt/hadoop/setup-hadoop.sh

  # DỊCH VỤ 2: YARN (RESOURCE MANAGER)
  yarn:
    build:
      context: .
      dockerfile: docker/yarn/Dockerfile
    depends_on:
      - hadoop
    hostname: resourcemanager
    volumes:
      - yarn_data:/usr/local/yarn/data
    networks:
      - hadoop_network
    ports:
      - "8088:8088"
    environment:
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      YARN_RESOURCEMANAGER_USER: root
      YARN_NODEMANAGER_USER: root
    command: bash -c "/usr/local/bin/setup-yarn.sh && /usr/local/hadoop/sbin/start-yarn.sh && tail -f /dev/null"

  # DỊCH VỤ 3: SPARK (MASTER)
  spark:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile
    depends_on:
      - hadoop
      - yarn
    hostname: sparkmaster
    volumes:
      - spark_data:/usr/local/spark/data
    networks:
      - hadoop_network
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64 
    command: bash -c "/opt/spark/setup-spark.sh && /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master && tail -f /dev/null"

networks:
  hadoop_network:
    name: hadoop-spark-net

volumes:
  hadoop_data:
  yarn_data:
  spark_data: